### ISSUE TITLE
Crash in v 0.4.0

### ISSUE THREAD

**Issue by kratman** [psi4/psi4public#240]
I figure this was probably caught already, but I thought I should submit a report just in case.

I was running some test calculations in psi4 (v 0.4.0, Ubuntu) and I got the following error while trying to calculate Mulliken charges:
```
[Screen output]

Traceback (most recent call last):
  File "<string>", line 58, in <module>
  File "/home/kratz/bin/miniconda/share/psi4/python/p4util/util.py", line 41, in oeprop
    oe = psi4.OEProp(wfn)
Boost.Python.ArgumentError: Python argument types in
    OEProp.__init__(OEProp, str)
did not match C++ signature:
    __init__(P7_object, N5boost10shared_ptrIN3psi12WavefunctionEEE)
```
The DFT calculation that ran before the Mulliken charges completed. Just the oeprop command failed.

This did not happen with an older copy on a different computer (PSI4 v 0.3.593, CentOS).  As I was typing this report I tried to reinstall psi4 from conda  on my CentOS machine, and I got a failure during the SAPT0 test calculations as well:
```
[Conda output]

  Report problems at http://forum.psicode.org/t/report-conda-update-psi4-oddities-here/32

Traceback (most recent call last):
  File "<string>", line 36, in <module>
  File "/wsu/home/ft/ft08/ft0805/work/exec/miniconda/miniconda/pkgs/psi4-0.3.593-py27_gab46761/share/psi4/python/driver.py", line 647, in energy
    procedures['energy'][lowername](lowername, **kwargs)
  File "/wsu/home/ft/ft08/ft0805/work/exec/miniconda/miniconda/pkgs/psi4-0.3.593-py27_gab46761/share/psi4/python/proc.py", line 3072, in run_sapt
    e_dimer = scf_helper('RHF', **kwargs)
  File "/wsu/home/ft/ft08/ft0805/work/exec/miniconda/miniconda/pkgs/psi4-0.3.593-py27_gab46761/share/psi4/python/proc.py", line 1972, in scf_helper
    e_scf = psi4.scf(precallback, postcallback)
Boost.Python.ArgumentError: Python argument types in
    psi4.scf(NoneType, NoneType)
did not match C++ signature:
    scf(N5boost10shared_ptrIN3psi12WavefunctionEEE, P7_object, P7_object)
```

-kratz

**Comment by loriab** [comment]
Thanks for the report. We did some considerable infrastructure changes that show up in `0.4` (hence the tag, so it'd be easy to let people know how to avoid them if they went wrong). The nature of the errors you're getting indicates they're definitely infrastructure-related. Could you post the input file for the oeprop error?

In trying to revert, even the architecture independent files (the python driver) will be inconsistent between pre and post `0.4`. So maybe try installing a `0.3` afresh into a new conda environment. And make sure you don't have `PSIDATADIR` envvar defined anywhere, just in case you occasionally work from cloned/compiled copies.

**Comment by kratman** [comment]
I leave most of the environment variable stuff for PSI4 in the hands of conda. I have a modified/compiled version of PSI4 on just one of my machines, but PSI4 crashes on all of them for one electron properties.

I saw the crash while I was running a testing script, so I know that it printed correct results for HF, PBE0, gradient, and PBE0+point-charges calculations. The only test of mine that failed involved recovering charges from a QM calculation.

```
[input file]


set_num_threads(8)
memory 256 mb
set reference rhf
set basis 6-31G*
set guess sad
set scf_type df

psi4_io.set_specific_path(32,'./')
psi4_io.set_specific_retention(32,True)
psi4_io.set_specific_path(180,'./')
psi4_io.set_specific_retention(180,True)

molecule LICHM_0 {
 0 1
 O 0.87273600000000 0.00000000000000 -1.2467539999999
 H 0.28827300000000 0.00000000000000 -2.0108530000000
 H 0.28827300000000 0.00000000000000 -0.4826550000000
 symmetry c1
 no_reorient
 no_com
}

Chrgfield = QMMM()
Chrgfield.extern.addCharge(-1.3062266666666,-0.6489658001839,0.00000001660701,1.10730418839000)
Chrgfield.extern.addCharge(0.35180666666666,-0.7534241883900,-0.0000000536004,1.26252019981607)
Chrgfield.extern.addCharge(0.86636000000000,-0.7788030060160,0.13229430272998,1.13268305579077)
Chrgfield.extern.addCharge(-1.3062266666666,-0.9086401998160,-0.0000000166070,1.15806181160999)
Chrgfield.extern.addCharge(0.10176666666666,-0.8041818116099,0.00000005360047,1.00284580018392)
Chrgfield.extern.addCharge(0.86636000000000,-0.7788029939839,-0.1322943027299,1.13268294420922)
Chrgfield.extern.addCharge(0.51284666666666,-0.7965191998160,0.76409898339298,1.73166981160999)
Chrgfield.extern.addCharge(-1.7440911751517,-0.6778443974775,0.64528811991560,1.64918444879139)
Chrgfield.extern.addCharge(0.85696271562354,-0.6894742127334,0.82228626070531,1.58968679653742)
Chrgfield.extern.addCharge(0.51284666666666,-0.5368448001839,0.76409901660701,1.68091218839000)
Chrgfield.extern.addCharge(-0.5989622639259,-0.6555196025224,0.88290988008439,1.76339755120860)
Chrgfield.extern.addCharge(0.67347739012079,-0.6438897872665,0.70591173929468,1.82289520346257)
Chrgfield.extern.addCharge(0.51284666666666,-0.7965191998160,-0.7640990166070,1.73166881160999)
Chrgfield.extern.addCharge(-0.5989622639259,-0.6555195917165,-0.8829099272347,1.76339645099940)
Chrgfield.extern.addCharge(0.85696271562354,-0.6894742074413,-0.8222861644302,1.58968574746033)
Chrgfield.extern.addCharge(0.51284666666666,-0.5368448001839,-0.7640989833929,1.68091118839000)
Chrgfield.extern.addCharge(-1.7440911751517,-0.6778444082834,-0.6452880727652,1.64918354900059)
Chrgfield.extern.addCharge(0.67347739012079,-0.6438897925586,-0.7059118355697,1.82289425253966)
psi4.set_global_option_python('EXTERN',Chrgfield.extern)

Eqm = energy('PBE0')
print('Energy: '+`Eqm`)
oeprop('MULLIKEN_CHARGES',bypass_scf=True)
```

```
[output file]

--------------------------------------------------------------------------

  Memory set to 256.000 MiB by Python script.

*** tstart() called on machtiani1
*** at Wed Feb 10 19:35:38 2016


         ---------------------------------------------------------
                                   SCF
            by Justin Turney, Rob Parrish, and Andy Simmonett
                              RKS Reference
                        8 Threads,    256 MiB Core
         ---------------------------------------------------------

  ==> Geometry <==

    Molecular point group: c1
    Full point group: Cs

    Geometry (in Angstrom), charge = 0, multiplicity = 1:

       Center              X                  Y                   Z               Mass       
    ------------   -----------------  -----------------  -----------------  -----------------
           O          0.872736000000     0.000000000000    -1.246754000000    15.994914619560
           H          0.288273000000     0.000000000000    -2.010853000000     1.007825032070
           H          0.288273000000     0.000000000000    -0.482655000000     1.007825032070

  Running in c1 symmetry.

  Rotational constants: A =     21.70025  B =      0.41373  C =      0.40599 [cm^-1]
  Rotational constants: A = 650557.09010  B =  12403.20112  C =  12171.15193 [MHz]
  Nuclear repulsion =    9.147558094236395

  Charge       = 0
  Multiplicity = 1
  Electrons    = 10
  Nalpha       = 5
  Nbeta        = 5

  ==> Algorithm <==

  SCF Algorithm Type is DF.
  DIIS enabled.
  MOM disabled.
  Fractional occupation disabled.
  Guess Type is SAD.
  Energy threshold   = 1.00e-06
  Density threshold  = 1.00e-06
  Integral threshold = 0.00e+00

  ==> Primary Basis <==

  Basis Set: 6-31G*
    Number of shells: 10
    Number of basis function: 19
    Number of Cartesian functions: 19
    Spherical Harmonics?: false
    Max angular momentum: 2

  ==> DFT Potential <==

   => PBE0 Composite Functional <= 

    PBE0 Hybrid GGA Exchange-Correlation Functional

    Adamo et. al., J. Chem. Phys., 110(13), 6158, 1999

    Points   =           5000
    Deriv    =              1
    GGA      =           TRUE
    Meta     =          FALSE

    X_LRC        =          FALSE
    X_Hybrid     =           TRUE
    X_Alpha      =   2.500000E-01
    X_Omega      =   0.000000E+00
    C_LRC        =          FALSE
    C_Hybrid     =          FALSE
    C_Alpha      =   0.000000E+00
    C_Omega      =   0.000000E+00

   => Exchange Functionals <=

    0.7500   PBE_X
    0.2500      HF 

   => Correlation Functionals <=

    1.0000   PBE_C

   => Molecular Quadrature <=

    Radial Scheme    =       TREUTLER
    Pruning Scheme   =           FLAT
    Nuclear Scheme   =       TREUTLER

    BS radius alpha  =              1
    Pruning alpha    =              1
    Radial Points    =             75
    Spherical Points =            302
    Total Points     =          65565
    Total Blocks     =             69
    Max Points       =           4576
    Max Functions    =             19

  ==> Pre-Iterations <==

   -------------------------------------------------------
    Irrep   Nso     Nmo     Nalpha   Nbeta   Ndocc  Nsocc
   -------------------------------------------------------
     A         19      19       0       0       0       0
   -------------------------------------------------------
    Total      19      19       5       5       5       0
   -------------------------------------------------------

  ==> Integral Setup <==

  ==> DFJK: Density-Fitted J/K Matrices <==

    J tasked:                  Yes
    K tasked:                  Yes
    wK tasked:                  No
    OpenMP threads:              8
    Integrals threads:           8
    Memory (MB):               183
    Algorithm:                Core
    Integral Cache:           NONE
    Schwarz Cutoff:          1E-12
    Fitting Condition:       1E-12

   => Auxiliary Basis Set <=

  Basis Set: 
    Number of shells: 42
    Number of basis function: 131
    Number of Cartesian functions: 131
    Spherical Harmonics?: false
    Max angular momentum: 3

   => External Potential Field:  <= 

    > Charges [a.u.] < 

              Z          x          y          z
       -1.30623   -0.64897    0.00000    1.10730
        0.35181   -0.75342   -0.00000    1.26252
        0.86636   -0.77880    0.13229    1.13268
       -1.30623   -0.90864   -0.00000    1.15806
        0.10177   -0.80418    0.00000    1.00285
        0.86636   -0.77880   -0.13229    1.13268
        0.51285   -0.79652    0.76410    1.73167
       -1.74409   -0.67784    0.64529    1.64918
        0.85696   -0.68947    0.82229    1.58969
        0.51285   -0.53684    0.76410    1.68091
       -0.59896   -0.65552    0.88291    1.76340
        0.67348   -0.64389    0.70591    1.82290
        0.51285   -0.79652   -0.76410    1.73167
       -0.59896   -0.65552   -0.88291    1.76340
        0.85696   -0.68947   -0.82229    1.58969
        0.51285   -0.53684   -0.76410    1.68091
       -1.74409   -0.67784   -0.64529    1.64918
        0.67348   -0.64389   -0.70591    1.82289

  Old nuclear repulsion        =    9.147558094236395
  Additional nuclear repulsion =   -0.220306557236836
  Total nuclear repulsion      =    8.927251536999558

  Minimum eigenvalue in the overlap matrix is 2.2467595935E-02.
  Using Symmetric Orthogonalization.
  SCF Guess: Superposition of Atomic Densities via on-the-fly atomic UHF.

  ==> Iterations <==

                           Total Energy        Delta E     RMS |[F,P]|

   @DF-RKS iter   0:   -76.25426884215133   -7.62543e+01   8.25166e-02 
   @DF-RKS iter   1:   -76.28225054480332   -2.79817e-02   2.00561e-02 
   @DF-RKS iter   2:   -76.24994640870842    3.23041e-02   2.57661e-02 DIIS
   @DF-RKS iter   3:   -76.33537346510494   -8.54271e-02   5.64978e-04 DIIS
   @DF-RKS iter   4:   -76.33541666733151   -4.32022e-05   7.02182e-05 DIIS
   @DF-RKS iter   5:   -76.33541734518556   -6.77854e-07   7.73497e-06 DIIS
   @DF-RKS iter   6:   -76.33541735566205   -1.04765e-08   1.19390e-06 DIIS
   @DF-RKS iter   7:   -76.33541735595242   -2.90370e-10   2.40194e-07 DIIS

  ==> Post-Iterations <==

    Orbital Energies (a.u.)
    -----------------------

    Doubly Occupied:                                                      

       1A    -19.184718     2A     -1.000452     3A     -0.509499  
       4A     -0.360493     5A     -0.281933  

    Virtual:                                                              

       6A      0.113651     7A      0.212439     8A      0.827371  
       9A      0.915633    10A      0.937398    11A      0.938267  
      12A      1.123156    13A      1.234184    14A      1.763048  
      15A      1.774444    16A      1.811716    17A      2.329295  
      18A      2.632599    19A      3.611500  

    Final Occupation by Irrep:
              A 
    DOCC [     5 ]

  Energy converged.

  @DF-RKS Final Energy:   -76.33541735595242

   => Energetics <=

    Nuclear Repulsion Energy =              8.9272515369995578
    One-Electron Energy =                -122.8414514085261118
    Two-Electron Energy =                  44.6070248999700425
    DFT Exchange-Correlation Energy =      -7.0282423843959076
    Empirical Dispersion Energy =           0.0000000000000000
    PCM Polarization Energy =               0.0000000000000000
    EFP Energy =                            0.0000000000000000
    Total Energy =                        -76.3354173559524156

    Alert: EFP and PCM quantities not currently incorporated into SCF psivars.

Properties will be evaluated at   0.000000,   0.000000,   0.000000 Bohr
  ==> Properties <==


Properties computed using the SCF density matrix

  Nuclear Dipole Moment: (a.u.)
     X:    14.2834      Y:     0.0000      Z:   -23.5602

  Electronic Dipole Moment: (a.u.)
     X:   -15.1523      Y:    -0.0000      Z:    23.6231

  Dipole Moment: (a.u.)
     X:    -0.8689      Y:    -0.0000      Z:     0.0628     Total:     0.8712

  Dipole Moment: (Debye)
     X:    -2.2085      Y:    -0.0000      Z:     0.1597     Total:     2.2143


  Saving occupied orbitals to File 180.

*** tstop() called on machtiani1 at Wed Feb 10 19:35:42 2016
Module time:
	user time   =      23.90 seconds =       0.40 minutes
	system time =       1.02 seconds =       0.02 minutes
	total time  =          4 seconds =       0.07 minutes
Total time:
	user time   =      23.90 seconds =       0.40 minutes
	system time =       1.02 seconds =       0.02 minutes
	total time  =          4 seconds =       0.07 minutes
[Error prints before oeprop]
```

The other crash I saw was just the input/output from the conda install test.

Let me know if you need more information.
-kratz

**Comment by loriab** [comment]
We're being a little more explicit about information-passing, and that influences oeprop. Change your ending lines to the below and all should be well. I'd say look at the installed samples, but I just remembered those didn't get updated until `0.4.3` or so, and our conda build machine is kaput so I can't update them for you. Sorry about that. I'll look into that SAPT install problem.

```
Eqm, wfn = energy('PBE0', return_wfn=True)
print('Energy: '+`Eqm`)
oeprop(wfn, 'MULLIKEN_CHARGES')
```

**Comment by loriab** [comment]
By the way, you're quite right to leave the PSIDATADIR business to conda. I only mentioned it because having that set is a way to lead the conda binary astray. I didn't have any problem with the SAPT test case upon install onto a fresh machine. Closing, but do reopen or start another issue if you've any further problems. Or for just questions about the new information-passing, try out forum.psicode.org . Thanks for helping us debug.

**Comment by kratman** [comment]
Thanks, I will update my input file writer.

**Comment by susilehtola** [comment]
Is there a 0.4.0 already out? I can't see one tagged here... When you make a new stable release, I'll update the Fedora packages.

**Comment by loriab** [comment]
We don't mean `0.4.0` as the new stable release. That will be `1.0.0`. The `0.4` tag (only on private at the moment) indicates some considerable data-passing changes. The sole public face of `0.4` at the moment is at https://anaconda.org/psi4/psi4/files .
