### ISSUE TITLE
PSIO_ERROR during fnocc energy calculation

### ISSUE THREAD

**Issue by jasonrig** [psi4/psi4public#34]
Hello,
This is Jason from Monash Uni again. Thought I'd post my issue here instead of emailing everyone. I'm getting a PSIO error for some FNO-CD-CCSD(T) calculations and I'm hoping someone could help solve my problem. See below for the details.

Cheers,
Jason

Input
```
memory 126 Gb
molecule complex {
*** Atomic coordinates omitted ***
}

set globals {
   basis aug-cc-pVDZ
   scf_type df
   df_basis_cc cholesky
   freeze_core True
   guess sad
   basis_guess 3-21G
}
energy('fno-df-ccsd(t)')
```

End of calculation output
```
*** at Mon Feb 10 13:17:33 2014



        *******************************************************
        *                                                     *
        *                       DF-CCSD                       *
        *                 Density-fitted CCSD                 *
        *                                                     *
        *                   Eugene DePrince                   *
        *                                                     *
        *******************************************************


  ==> 3-index integrals <==

        Generating Cholesky vectors ...
        Cholesky decomposition threshold: 1.00e-04
        Number of Cholesky vectors:           2784

  ==> Frozen Natural Orbitals <==

        Doubles contribution to MP2 energy in full space:      -4.157303195170

        Cutoff for significant NO occupancy: 1.000e-06

        Number of virtual orbitals in original space:    678
        Number of virtual orbitals in truncated space:   640

  ==> Memory <==

        Total memory requirements:        78825.79 mb
        3-index integrals:                10109.75 mb
        CCSD intermediates:               68716.04 mb


        <<< warning! >>> switched to low-memory (t) algorithm

        memory requirements for CCSD(T):  36451.32 mb

  ==> Input parameters <==

        Freeze core orbitals?                 yes
        Use frozen natural orbitals?          yes
        r_convergence:                  1.000e-07
        e_convergence:                  1.000e-06
        Number of DIIS vectors:                 8
        Number of frozen core orbitals:        26
        Number of active occupied orbitals:    74
        Number of active virtual orbitals:    640
        Number of frozen virtual orbitals:     38


  Begin singles and doubles coupled cluster iterations

   Iter  DIIS          Energy       d(Energy)          |d(T)|     time
      0   0 2    0.0000000000    0.0000000000    0.0000000000      393

  CCSD iterations converged!

        T1 diagnostic:                        0.000000000000
        D1 diagnostic:                        0.000000000000

        OS MP2 FNO correction:               -3.045395864164
        SS MP2 FNO correction:               -1.111907331006
        MP2 FNO correction:                  -4.157303195170

        OS MP2 correlation energy:           -3.045395864164
        SS MP2 correlation energy:           -1.111907331006
        MP2 correlation energy:              -4.157303195170
      * MP2 total energy:                 -1500.355601695273

        OS CCSD correlation energy:          -3.045395864164
        SS CCSD correlation energy:          -1.111907331006
        CCSD correlation energy:             -4.157303195170
      * CCSD total energy:                -1500.355601695273

  Total time for CCSD iterations:    3404.15 s (user)
                                      270.93 s (system)
                                         607 s (total)

  Time per iteration:                    inf s (user)
                                         inf s (system)
                                         inf s (total)

*** tstop() called on r3546 at Mon Feb 10 14:43:17 2014
Module time:
	user time   =   31046.70 seconds =     517.45 minutes
	system time =     945.63 seconds =      15.76 minutes
	total time  =       5144 seconds =      85.73 minutes
Total time:
	user time   =   33202.74 seconds =     553.38 minutes
	system time =     990.31 seconds =      16.51 minutes
	total time  =       5317 seconds =      88.62 minutes

*** tstart() called on r3546
*** at Mon Feb 10 14:57:28 2014


        *******************************************************
        *                                                     *
        *                      CCSD(T)                        *
        *                                                     *
        *******************************************************

        num_threads =                    16
        available memory =      83711.64 mb
        memory requirements =   36451.32 mb

```

PSIO error (from stderr)
```
PSIO_ERROR: unit = 260, errval = 18
PSIO_ERROR: 18 (Incorrect block end address)
Traceback (most recent call last):
  File "<string>", line 77, in <module>
  File "/apps/psicode/4.0b5.1/share/psi/python/driver.py", line 570, in energy
    procedures['energy'][lowername](lowername, **kwargs)
  File "/apps/psicode/4.0b5.1/share/psi/python/proc.py", line 2289, in run_fnodfcc
    psi4.fnocc()
RuntimeError: PSIO Error
file: /short/z00/cyl900/psi4/psi4public/src/lib/libpsio/error.cc
line: 1p
```

**Comment by rxk900** [comment]
Any news on this?
Another of our users has hit this bug(?), diagnosed by
PSIO_ERROR: unit = 255, errval = 17
PSIO_ERROR: 17 (Incorrect block start address)
at the triples stage.
Their job appears to be slightly bigger so don't think providing their input will add to this.

**Comment by edeprince3** [comment]
No progress, but it is back on my radar again.

**Comment by amjames** [comment]
@edeprince3 is this still an issue?

**Comment by edeprince3** [comment]
I have a slightly modified version of the original problem running now.  It is happily chugging along in the (T) portion, which is passed the point of the problem in the original output.  Once I see it is finished with at least 10% of (T), I'll close the ticket.

**Comment by edeprince3** [comment]
OK, I'm satisfied and closing this one.
